"""
Computational grid.

Implements Section 5 of the paper (interface-fitted / uniform collocated grid).

For the uniform case (``alpha_grid = 1.0``) the grid spacing is simply
``h[ax] = L[ax] / N[ax]`` and node coordinates are
``x[ax] = linspace(0, L[ax], N[ax]+1)``.

For the interface-fitted case (``alpha_grid > 1.0``) a smooth grid density
function ω(φ) = exp(−α·(φ/ε)²) concentrates nodes near the interface.
The physical coordinate is obtained by integrating a scaled spacing field
and renormalising to the domain length.  A minimum cell-width floor
``dx_min_floor`` prevents near-zero spacings that would make the CCD
system ill-conditioned (Known Issue #3 in the architecture document).

Key equations:
    Uniform:  Δx = L / N                                         (§5 baseline)
    Grid density: ω(φ) = exp(−α·(φ/ε)²)                         (§5 Eq.~grid)
    Metric:   J = ∂ξ/∂x  (used by CCD for non-uniform spacing)  (§4.9)
"""

from __future__ import annotations
import math
import numpy as np
from typing import TYPE_CHECKING, Tuple

from .metrics import compute_metrics

if TYPE_CHECKING:
    from ..backend import Backend
    from ..config import GridConfig


class Grid:
    """Collocated Cartesian grid (2-D or 3-D).

    Attributes
    ----------
    ndim : int
    N : tuple[int, ...]  — number of cells per axis (nodes = N+1)
    L : tuple[float, ...] — domain lengths
    h : list[numpy.ndarray] — 1-D spacing arrays, shape (N[ax]+1,) each
    coords : list[numpy.ndarray] — node coordinate vectors, shape (N[ax]+1,)
    shape : tuple[int, ...] — (N[0]+1, N[1]+1[, N[2]+1])
    J : list[numpy.ndarray] — metric ∂ξ/∂x per axis (= 1/h for uniform)
    dJ_dxi : list[numpy.ndarray] — gradient of metric in ξ-space
    """

    def __init__(self, grid_config: "GridConfig", backend: "Backend"):
        self._gc = grid_config
        self.backend = backend
        self.xp = backend.xp

        self.ndim = grid_config.ndim
        self.N = tuple(grid_config.N)
        self.L = tuple(grid_config.L)

        # Build uniform grid (interface-fitted update happens separately)
        self.coords: list[np.ndarray] = []
        self.h: list[np.ndarray] = []
        for ax in range(self.ndim):
            c = np.linspace(0.0, grid_config.L[ax], grid_config.N[ax] + 1)
            self.coords.append(c)
            # h[ax] is length-N[ax] spacing (between consecutive nodes)
            # We store per-node spacing (averaged from both sides) for metrics
            dx = np.full(grid_config.N[ax] + 1, grid_config.L[ax] / grid_config.N[ax])
            self.h.append(dx)

        self.shape: tuple = tuple(n + 1 for n in self.N)
        self._cell_volumes = None

        # Metrics (identity for uniform grid)
        self._build_metrics()

    # ── Public interface ──────────────────────────────────────────────────

    def meshgrid(self) -> Tuple:
        """Return open meshgrid arrays in physical coordinates.

        2-D: returns (X, Y) each shape ``(N[0]+1, N[1]+1)``.
        3-D: returns (X, Y, Z) each shape ``(N[0]+1, N[1]+1, N[2]+1)``.

        Output arrays live on the backend device: NumPy on CPU backend,
        CuPy on GPU backend.  ``self.coords`` stays on host for the
        metric-building path; conversion happens only at this boundary.
        """
        xp = self.xp
        return xp.meshgrid(*[xp.asarray(c) for c in self.coords], indexing="ij")

    def update_from_levelset(
        self,
        psi_data: np.ndarray,
        eps: float,
        ccd=None,
    ) -> None:
        """Rebuild interface-fitted grid given the Heaviside field ψ.

        Only active when ``grid_config.alpha_grid > 1.0``.

        Internally converts ψ → φ via logit inversion, then applies the
        paper's Gaussian grid density (§6 eq:grid_delta):
            δ*(φ) = exp(−φ²/ε_g²) / (ε_g√π),  ε_g = eps_g_factor × ε
            ω_a = 1 + (α_a−1) · δ*(φ̄_a)
        on axes enabled by ``grid_config.fitting_axes``. Disabled axes are kept
        exactly uniform, giving a separable map
        ``x_a = X_a(ξ_a)`` for active axes and ``x_a = L_a ξ_a`` otherwise.
        Active axes are regenerated by equidistributing the physical monitor
        ``ω_a(x_a)`` over the current coordinates, so dynamic rebuilds follow
        the currently tracked interface rather than a stale array index.

        Parameters
        ----------
        psi_data : array — Heaviside field ψ ∈ [0, 1]
        eps      : interface half-width ε
        ccd      : CCDSolver instance for O(h⁶) metric evaluation (optional)
        """
        from ..levelset.heaviside import invert_heaviside

        alpha = self._gc.alpha_grid
        if alpha <= 1.0:
            return  # uniform grid — nothing to do
        fitting_axes = tuple(bool(enabled) for enabled in self._gc.fitting_axes)
        if not any(fitting_axes):
            return

        xp = self.backend.xp

        fitting_alpha = tuple(float(value) for value in self._gc.fitting_alpha_grid)
        fitting_eps_factor = tuple(float(value) for value in self._gc.fitting_eps_g_factor)
        fitting_eps_cells = tuple(self._gc.fitting_eps_g_cells)
        fitting_dx_floor = tuple(float(value) for value in self._gc.fitting_dx_min_floor)

        # ψ → φ (logit inversion) on the active backend. We only materialise
        # the final 1-D per-axis coordinates on host for metric construction.
        phi = invert_heaviside(xp, xp.asarray(psi_data), eps)

        for ax in range(self.ndim):
            alpha_axis = fitting_alpha[ax]
            if not fitting_axes[ax] or alpha_axis <= 1.0:
                self._reset_axis_to_uniform(ax)
                continue

            eps_g_cells = fitting_eps_cells[ax]
            if eps_g_cells is not None:
                h_uniform = self._gc.L[ax] / self._gc.N[ax]
                eps_g = eps_g_cells * h_uniform
            else:
                eps_g = fitting_eps_factor[ax] * eps

            # 1-D marginal: min |φ| over other axes (§6 φ̄^x_i = min_j |φ_{i,j}|)
            axes_other = tuple(a for a in range(self.ndim) if a != ax)
            phi_1d = xp.min(xp.abs(phi), axis=axes_other)

            phi_1d_h = np.asarray(self.backend.to_host(phi_1d))
            phi_h = np.asarray(self.backend.to_host(phi))
            coords_old = np.asarray(self.coords[ax], dtype=float)

            # §6 eq:grid_delta: bounded Gaussian indicator ∈ [0, 1]
            # NOTE: ディラックデルタ正規化因子 1/(ε_g√π) は除去する.
            # 正規化すると ピーク = 1/(ε_g√π) >> 1 となり ω >> α になる (unbounded bug).
            indicator_1d = np.exp(-(phi_1d_h ** 2) / (eps_g ** 2))
            indicator_1d = np.maximum(
                indicator_1d,
                self._closure_seed_indicator_1d(phi_h, ax, eps_g),
            )
            omega = 1.0 + (alpha_axis - 1.0) * indicator_1d  # ω ∈ [1, α_a]

            # Equidistribution on the physical old coordinate:
            #     ∫_0^{x_i} ω_a(s) ds = i/N_a ∫_0^L ω_a(s) ds.
            # This keeps Mode-2 rebuilds attached to the tracked interface
            # position on non-uniform grids, not to the raw node index.
            monitor_cell = 0.5 * (omega[:-1] + omega[1:]) * np.diff(coords_old)
            monitor_cdf = np.zeros(self._gc.N[ax] + 1, dtype=float)
            monitor_cdf[1:] = np.cumsum(monitor_cell)
            target = np.linspace(0.0, monitor_cdf[-1], self._gc.N[ax] + 1)
            coords_ax_h = np.interp(target, monitor_cdf, coords_old)
            coords_ax_h[0] = 0.0
            coords_ax_h[-1] = self._gc.L[ax]

            cell_dx = np.diff(coords_ax_h)
            cell_dx = self._apply_cell_width_floor(
                cell_dx,
                fitting_dx_floor[ax],
                self._gc.L[ax],
            )
            coords_ax_h = np.zeros(self._gc.N[ax] + 1, dtype=float)
            coords_ax_h[1:] = np.cumsum(cell_dx)
            coords_ax_h[-1] = self._gc.L[ax]

            self.coords[ax] = coords_ax_h
            # Per-node spacing (average of left and right cell widths)
            node_dx = np.empty(self._gc.N[ax] + 1)
            node_dx[0] = cell_dx[0]
            node_dx[-1] = cell_dx[-1]
            node_dx[1:-1] = 0.5 * (cell_dx[:-1] + cell_dx[1:])
            self.h[ax] = node_dx

        self._build_metrics(ccd=ccd)

    # ── Private helpers ───────────────────────────────────────────────────

    def _reset_axis_to_uniform(self, axis: int) -> None:
        """Keep an inactive fitting axis on the exact uniform coordinate map."""
        coords_axis = np.linspace(0.0, self._gc.L[axis], self._gc.N[axis] + 1)
        self.coords[axis] = coords_axis
        self.h[axis] = np.full(
            self._gc.N[axis] + 1,
            self._gc.L[axis] / self._gc.N[axis],
        )

    @staticmethod
    def _apply_cell_width_floor(
        cell_widths: np.ndarray,
        floor: float,
        length: float,
    ) -> np.ndarray:
        """Enforce a positive physical cell-width floor while preserving length."""
        if floor <= 0.0 or np.min(cell_widths) >= floor:
            return cell_widths
        n_cells = cell_widths.size
        if floor * n_cells >= length:
            return np.full(n_cells, length / n_cells)
        surplus = np.maximum(cell_widths - floor, 0.0)
        total_surplus = surplus.sum()
        if total_surplus <= 0.0:
            return np.full(n_cells, length / n_cells)
        scale = (length - floor * n_cells) / total_surplus
        return floor + surplus * scale

    def _closure_seed_indicator_1d(
        self,
        phi: np.ndarray,
        axis: int,
        eps_g: float,
    ) -> np.ndarray:
        """Build a Gaussian monitor from closed-domain interface crossings."""
        coords_axis = np.asarray(self.coords[axis], dtype=float)
        indicator = np.zeros_like(coords_axis)
        if self.ndim != 2:
            return indicator

        coords_x = np.asarray(self.coords[0], dtype=float)
        coords_y = np.asarray(self.coords[1], dtype=float)
        projections = []
        tol = max(1.0e-12, 1.0e-10 * eps_g)

        phi_left = phi[:-1, :]
        phi_right = phi[1:, :]
        crossing_mask = (phi_left * phi_right) < 0.0
        if np.any(crossing_mask):
            crossing_i, crossing_j = np.where(crossing_mask)
            denom = np.abs(phi_left[crossing_i, crossing_j]) + np.abs(phi_right[crossing_i, crossing_j])
            frac = np.abs(phi_left[crossing_i, crossing_j]) / np.where(denom > 0.0, denom, 1.0)
            crossing_x = coords_x[crossing_i] + frac * (coords_x[crossing_i + 1] - coords_x[crossing_i])
            crossing_y = coords_y[crossing_j]
            projections.append(crossing_x if axis == 0 else crossing_y)

        phi_down = phi[:, :-1]
        phi_up = phi[:, 1:]
        crossing_mask = (phi_down * phi_up) < 0.0
        if np.any(crossing_mask):
            crossing_i, crossing_j = np.where(crossing_mask)
            denom = np.abs(phi_down[crossing_i, crossing_j]) + np.abs(phi_up[crossing_i, crossing_j])
            frac = np.abs(phi_down[crossing_i, crossing_j]) / np.where(denom > 0.0, denom, 1.0)
            crossing_x = coords_x[crossing_i]
            crossing_y = coords_y[crossing_j] + frac * (coords_y[crossing_j + 1] - coords_y[crossing_j])
            projections.append(crossing_x if axis == 0 else crossing_y)

        zero_i, zero_j = np.where(np.abs(phi) <= tol)
        if len(zero_i) > 0:
            projections.append(coords_x[zero_i] if axis == 0 else coords_y[zero_j])

        if not projections:
            return indicator
        projected = np.concatenate(projections)
        if projected.size == 0:
            return indicator
        distance = coords_axis.reshape(-1, 1) - projected.reshape(1, -1)
        return np.max(np.exp(-(distance * distance) / (eps_g * eps_g)), axis=1)

    def _build_metrics(self, ccd=None) -> None:
        """Compute CCD metrics J = dxi/dx and dJ/dxi for each axis.

        Delegates to core.metrics.compute_metrics() (SRP extraction).
        """
        self.J, self.dJ_dxi = compute_metrics(
            self.coords, self.h, self.N, self.ndim, self.uniform, ccd,
        )
        self._cell_volumes = self._build_cell_volume_field()

    # ── Convenience ──────────────────────────────────────────────────────

    @property
    def uniform(self) -> bool:
        """True when the grid is uniform (alpha_grid ≤ 1)."""
        return self._gc.alpha_grid <= 1.0

    def cell_volume(self) -> float:
        """Approximate uniform cell volume (product of mean spacings)."""
        return math.prod(L / N for L, N in zip(self.L, self.N))

    def cell_volumes(self):
        """Per-node control volumes retained by the current grid geometry."""
        if self._cell_volumes is not None:
            return self._cell_volumes
        self._cell_volumes = self._build_cell_volume_field()
        return self._cell_volumes

    def _build_cell_volume_field(self):
        """Materialize the control-volume field produced by this grid build."""
        xp = self.xp
        vol = xp.asarray(self.h[0])
        for ax in range(1, self.ndim):
            vol = xp.expand_dims(vol, axis=ax) * xp.asarray(self.h[ax])
        return vol

    def __repr__(self) -> str:
        h_str = " × ".join(
            f"{self.L[ax]/self.N[ax]:.4g}" for ax in range(self.ndim)
        )
        return f"Grid(ndim={self.ndim}, N={self.N}, L={self.L}, h≈{h_str})"
