# interface/SolverAPI_v1.py — L→E Interface Contract Template
# Generated by EnvMetaBootstrapper. Filled in by L-Domain Gatekeeper (CodeWorkflowCoordinator).
# Status: {pending} — not yet signed
#
# IF-AGREEMENT:
#   feature:      Solver API contract for E-Domain consumption
#   domain:       L→E
#   gatekeeper:   CodeWorkflowCoordinator
#   specialist:   ExperimentRunner
#   inputs:
#     - interface/AlgorithmSpecs.md: signed T→L contract (precondition)
#     - src/twophase/: solver implementation
#   outputs:
#     - interface/SolverAPI_v1.py: signed solver API definition
#   success_criteria: TestRunner PASS on all unit/integration tests
#   created_at:   {pending}
#   signed_by:    {pending — BLOCK E-Domain until signed}

from abc import ABC, abstractmethod
from typing import Any

class SolverAPI(ABC):
    """
    Abstract interface contract: L→E.
    ExperimentRunner must consume the solver ONLY through this interface.
    Direct access to src/twophase/ internals from E-Domain = CONTAMINATION violation (A9).

    Status: {pending} — fill in after L-Domain pipeline completes.
    """

    @abstractmethod
    def step_forward(self, dt: float) -> None:
        """Advance solver by one time step dt."""
        ...

    @abstractmethod
    def get_state(self) -> dict[str, Any]:
        """Return current solver state as a dictionary of named arrays."""
        ...

    @abstractmethod
    def get_diagnostics(self) -> dict[str, float]:
        """Return scalar diagnostics (mass, energy, pressure jump, etc.)."""
        ...
