"""Config-driven simulation runner.

Keeps experiment orchestration separate from ``TwoPhaseNSSolver`` so the solver
class only owns scheme composition and one-step advancement.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from .config_io import ExperimentConfig


def run_simulation(
    cfg: "ExperimentConfig",
    *,
    resume_from: str | Path | None = None,
    checkpoint_path: str | Path | None = None,
    checkpoint_every_steps: int | None = None,
    config_path: str | Path | None = None,
) -> dict:
    """Run a complete simulation from an :class:`ExperimentConfig`."""
    from .checkpoint import CheckpointError, load_checkpoint, save_checkpoint
    from .ns_pipeline import TwoPhaseNSSolver
    from .ns_step_state import NSStepRequest
    from ..levelset.wall_contact import WallContactSet
    from ..tools.diagnostics import DiagnosticCollector

    if (resume_from or checkpoint_path or checkpoint_every_steps) and config_path is None:
        raise CheckpointError("checkpointed ch14 runs require the source config path")

    solver = TwoPhaseNSSolver.from_config(cfg)
    resume_state = None
    if resume_from is not None:
        resume_state = load_checkpoint(resume_from, solver=solver, config_path=config_path)
        print(
            f"  [resume] loaded {resume_from} at "
            f"step={resume_state['step']} t={resume_state['t']:.8g}"
        )

    psi = resume_state["psi"] if resume_state else solver.build_ic(cfg)
    psi_initial_host = np.asarray(solver._backend.to_host(psi))
    if not resume_state:
        wall_contacts = WallContactSet.detect_from_psi(
            psi_initial_host,
            solver._grid,
            bc_type=solver.bc_type,
        )
        solver.set_wall_contacts(wall_contacts)
    if resume_state:
        u, v = resume_state["u"], resume_state["v"]
        p = resume_state["p"]
    else:
        u, v = solver.build_velocity(cfg, psi)
        p = None
    bc_hook = solver.make_bc_hook(cfg)
    ph = cfg.physics

    if solver._alpha_grid > 1.0 and not resume_state:
        psi, u, v = solver._rebuild_grid(psi, u, v, ph.rho_l, ph.rho_g)
        mode = "static" if solver._rebuild_freq == 0 else f"dynamic/{solver._rebuild_freq}"
        print(f"  [{mode} non-uniform] grid built from IC, h_min={solver.h_min:.4e}")

    ic = cfg.initial_condition
    R_ic = float(ic.get("radius", 0.25)) if isinstance(ic, dict) else 0.25

    _bk0 = solver._backend
    diag = DiagnosticCollector(
        cfg.diagnostics,
        solver.X,
        solver.Y,
        solver.h,
        rho_l=ph.rho_l,
        rho_g=ph.rho_g,
        sigma=ph.sigma,
        R=R_ic,
    )
    # Retain geometry generated by this grid build as an explicit run artifact.
    if diag.needs_retained_geometry():
        diag.retain_device_geometry(_bk0.xp, solver.X, solver.Y, psi.shape)
    snaps: list[dict] = list(resume_state["snapshots"]) if resume_state else []
    if cfg.run.snap_interval is not None and cfg.run.T_final is not None:
        iv = cfg.run.snap_interval
        n = int(cfg.run.T_final / iv)
        auto = [i * iv for i in range(n + 1)]
        snap_times = sorted(set(list(cfg.run.snap_times) + auto))
    else:
        snap_times = list(cfg.run.snap_times)
    snap_idx = 0
    if resume_state:
        while snap_idx < len(snap_times) and snap_times[snap_idx] <= resume_state["t"]:
            snap_idx += 1

    T = cfg.run.T_final if cfg.run.T_final is not None else float("inf")
    max_steps = cfg.run.max_steps

    t = float(resume_state["t"]) if resume_state else 0.0
    step = int(resume_state["step"]) if resume_state else 0
    previous_results = resume_state["results"] if resume_state else {}
    dbg_history: list = list(resume_state["debug_history"]) if resume_state else []
    # Retain per-node control volumes from the current grid build for reuse.
    control_volumes = solver._grid.cell_volumes() if solver._alpha_grid > 1.0 else None

    while t < T and (max_steps is None or step < max_steps):
        dt_budget = None
        if cfg.run.dt_fixed is not None:
            dt = min(cfg.run.dt_fixed, T - t)
        else:
            dt_budget = solver.dt_budget(
                u,
                v,
                ph,
                cfg.run.cfl,
                cfl_advective=cfg.run.cfl_advective,
                cfl_capillary=cfg.run.cfl_capillary,
                cfl_viscous=cfg.run.cfl_viscous,
            )
            dt = min(dt_budget.dt, T - t)
        if dt < 1e-12:
            break

        step_index = step
        grid_will_rebuild = (
            solver._alpha_grid > 1.0
            and solver._rebuild_freq > 0
            and step_index > 0
            and (step_index % solver._rebuild_freq == 0)
        )
        psi, u, v, p = solver.step_request(
            NSStepRequest(
                psi=psi,
                u=u,
                v=v,
                dt=dt,
                rho_l=ph.rho_l,
                rho_g=ph.rho_g,
                sigma=ph.sigma,
                mu=ph.mu,
                g_acc=ph.g_acc,
                rho_ref=ph.rho_ref,
                mu_l=ph.mu_l,
                mu_g=ph.mu_g,
                bc_hook=bc_hook,
                step_index=step_index,
            ),
            return_host_pressure=False,
        )
        t += dt
        step += 1

        _bk = solver._backend
        if grid_will_rebuild:
            control_volumes = solver._grid.cell_volumes()
            if diag.needs_retained_geometry():
                diag.X = solver.X
                diag.Y = solver.Y
                diag.retain_device_geometry(_bk.xp, solver.X, solver.Y, psi.shape)
        diag.collect(t, psi, u, v, _bk.xp.asarray(p), dV=control_volumes)
        dbg_entry = solver._step_diag.last
        if dbg_entry or (cfg.run.debug_diagnostics and dt_budget is not None):
            merged_diag = {"t": t, "step": step, **dbg_entry}
            if cfg.run.debug_diagnostics and dt_budget is not None:
                merged_diag.update(dt_budget.diagnostics())
            dbg_history.append(merged_diag)

        while snap_idx < len(snap_times) and t >= snap_times[snap_idx]:
            _to_h = lambda a: np.asarray(_bk.to_host(a))
            psi_h, u_h, v_h, p_h = _to_h(psi), _to_h(u), _to_h(v), _to_h(p)
            snap_entry = {
                "t": float(t),
                "psi": psi_h.copy(),
                "u": u_h.copy(),
                "v": v_h.copy(),
                "p": p_h.copy(),
                "rho": (ph.rho_l * psi_h + ph.rho_g * (1.0 - psi_h)).copy(),
            }
            if solver._p_prev_accel_face_components is not None:
                snap_entry["pressure_accel_faces"] = [
                    _to_h(component).copy()
                    for component in solver._p_prev_accel_face_components
                ]
            if solver._alpha_grid > 1.0:
                snap_entry["grid_coords"] = [c.copy() for c in solver._grid.coords]
            snaps.append(snap_entry)
            snap_idx += 1

        if step % cfg.run.print_every == 0 or step <= 2:
            ke = diag.last("kinetic_energy", 0.0)
            print(f"  step={step:5d}  t={t:.4f}  dt={dt:.5f}  KE={ke:.3e}")
            if dt_budget is not None:
                print(
                    f"          dt_adv={dt_budget.dt_advective:.3e}  "
                    f"dt_visc={dt_budget.dt_viscous:.3e}  "
                    f"dt_cap={dt_budget.dt_capillary:.3e}  "
                    f"limiter={dt_budget.limiter}"
                )
            d = solver._step_diag.last
            if d:
                print(
                    f"          kappa_max={d['kappa_max']:.3e}  "
                    f"ppe_rhs={d['ppe_rhs_max']:.3e}  "
                    f"bf_res={d['bf_residual_max']:.3e}  "
                    f"div_u={d['div_u_max']:.3e}"
                )

        ke = diag.last("kinetic_energy", 0.0)
        if np.isnan(ke) or ke > 1e6:
            print(f"  BLOWUP at step={step}, t={t:.4f}")
            break
        if (
            checkpoint_every_steps is not None
            and checkpoint_path is not None
            and checkpoint_every_steps > 0
            and step % checkpoint_every_steps == 0
        ):
            current_results = _merge_time_series(
                previous_results,
                {**diag.to_arrays()},
            )
            save_checkpoint(
                checkpoint_path,
                solver=solver,
                psi=psi,
                u=u,
                v=v,
                p=p,
                t=t,
                step=step,
                config_path=config_path,
                results=current_results,
                snapshots=snaps,
                debug_history=dbg_history,
            )

    results = _merge_time_series(previous_results, {**diag.to_arrays()})
    results["snapshots"] = snaps
    if dbg_history:
        results["debug_diagnostics"] = {
            key: np.array([entry[key] for entry in dbg_history]) for key in dbg_history[0]
        }
    if checkpoint_path is not None:
        p_save = p if p is not None else solver._backend.xp.zeros_like(psi)
        save_checkpoint(
            checkpoint_path,
            solver=solver,
            psi=psi,
            u=u,
            v=v,
            p=p_save,
            t=t,
            step=step,
            config_path=config_path,
            results={k: v for k, v in results.items() if isinstance(v, np.ndarray)},
            snapshots=snaps,
            debug_history=dbg_history,
        )
    return results


def _merge_time_series(
    previous: dict[str, np.ndarray],
    current: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Concatenate diagnostic arrays loaded from checkpoint with new samples."""
    merged: dict[str, np.ndarray] = {}
    for key, value in previous.items():
        if isinstance(value, np.ndarray):
            merged[key] = value.copy()
    for key, value in current.items():
        if not isinstance(value, np.ndarray):
            continue
        if key in merged and merged[key].ndim == value.ndim:
            merged[key] = np.concatenate([merged[key], value])
        else:
            merged[key] = value
    return merged
