"""Config-driven simulation runner.

Keeps experiment orchestration separate from ``TwoPhaseNSSolver`` so the solver
class only owns scheme composition and one-step advancement.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from .snapshot_payload import PROJECTION_SNAPSHOT_FIELDS

if TYPE_CHECKING:
    from .config_io import ExperimentConfig


BLOWUP_KINETIC_ENERGY_LIMIT = 1.0e6
PRE_BLOWUP_CHECKPOINT_FRACTION = 1.0e-2


def run_simulation(
    cfg: "ExperimentConfig",
    *,
    resume_from: str | Path | None = None,
    checkpoint_path: str | Path | None = None,
    checkpoint_every_steps: int | None = None,
    checkpoint_interval: float | None = None,
    config_path: str | Path | None = None,
) -> dict:
    """Run a complete simulation from an :class:`ExperimentConfig`."""
    from .checkpoint import (
        CheckpointError,
        capture_checkpoint_frame,
        load_checkpoint,
        save_checkpoint,
        write_checkpoint_frame,
    )
    from .ns_pipeline import TwoPhaseNSSolver
    from .ns_step_state import NSStepRequest
    from ..levelset.wall_contact import WallContactSet
    from ..tools.diagnostics import DiagnosticCollector

    checkpoint_interval = _normalise_checkpoint_interval(
        checkpoint_interval
        if checkpoint_interval is not None
        else getattr(getattr(cfg, "output", None), "checkpoint_interval", None)
    )
    if (
        resume_from
        or checkpoint_path
        or checkpoint_every_steps
        or checkpoint_interval is not None
    ) and config_path is None:
        raise CheckpointError("checkpointed ch14 runs require the source config path")

    solver = TwoPhaseNSSolver.from_config(cfg)
    resume_state = None
    resume_dt_candidate = None
    if resume_from is not None:
        resume_state = load_checkpoint(resume_from, solver=solver, config_path=config_path)
        if resume_state.get("state_phase") != "pre_step":
            raise CheckpointError(
                "--resume-from requires a pre-step continuation checkpoint; "
                "post-step checkpoints are analysis artifacts and may include "
                "a terminally shortened timestep"
            )
        resume_dt_candidate = resume_state.get("dt_candidate")
        print(
            f"  [resume] loaded {resume_from} at "
            f"step={resume_state['step']} t={resume_state['t']:.8g} "
            f"phase={resume_state['state_phase']}"
        )
    continuation_path = (
        _continuation_checkpoint_path(checkpoint_path)
        if checkpoint_path is not None
        else None
    )
    pre_blowup_path = (
        _pre_blowup_checkpoint_path(checkpoint_path)
        if checkpoint_path is not None
        else None
    )
    if resume_from is None and pre_blowup_path is not None and pre_blowup_path.exists():
        pre_blowup_path.unlink()
    if resume_from is None and continuation_path is not None and continuation_path.exists():
        continuation_path.unlink()

    psi = resume_state["psi"] if resume_state else solver.build_ic(cfg)
    psi_initial_host = np.asarray(solver._backend.to_host(psi))
    if not resume_state:
        wall_contacts = WallContactSet.detect_from_psi(
            psi_initial_host,
            solver._grid,
            bc_type=solver.bc_type,
        )
        solver.set_wall_contacts(wall_contacts)
    if resume_state:
        u, v = resume_state["u"], resume_state["v"]
        p = resume_state["p"]
    else:
        u, v = solver.build_velocity(cfg, psi)
        p = None
    bc_hook = solver.make_bc_hook(cfg)
    ph = cfg.physics

    if solver._alpha_grid > 1.0 and not resume_state:
        psi, u, v = solver._rebuild_grid(psi, u, v, ph.rho_l, ph.rho_g)
        mode = "static" if solver._rebuild_freq == 0 else f"dynamic/{solver._rebuild_freq}"
        print(f"  [{mode} non-uniform] grid built from IC, h_min={solver.h_min:.4e}")

    ic = cfg.initial_condition
    R_ic = float(ic.get("radius", 0.25)) if isinstance(ic, dict) else 0.25

    _bk0 = solver._backend
    diag = DiagnosticCollector(
        cfg.diagnostics,
        solver.X,
        solver.Y,
        solver.h,
        rho_l=ph.rho_l,
        rho_g=ph.rho_g,
        sigma=ph.sigma,
        R=R_ic,
    )
    # Retain geometry generated by this grid build as an explicit run artifact.
    if diag.needs_retained_geometry():
        diag.retain_device_geometry(_bk0.xp, solver.X, solver.Y, psi.shape)
    snaps: list[dict] = list(resume_state["snapshots"]) if resume_state else []
    if cfg.run.snap_interval is not None and cfg.run.T_final is not None:
        iv = cfg.run.snap_interval
        n = int(cfg.run.T_final / iv)
        auto = [i * iv for i in range(n + 1)]
        snap_times = sorted(set(list(cfg.run.snap_times) + auto))
    else:
        snap_times = list(cfg.run.snap_times)
    snap_idx = 0
    if resume_state:
        while snap_idx < len(snap_times) and snap_times[snap_idx] <= resume_state["t"]:
            snap_idx += 1

    T = cfg.run.T_final if cfg.run.T_final is not None else float("inf")
    max_steps = cfg.run.max_steps

    t = float(resume_state["t"]) if resume_state else 0.0
    step = int(resume_state["step"]) if resume_state else 0
    next_time_checkpoint = _next_time_checkpoint(t, checkpoint_interval, T)
    previous_results = resume_state["results"] if resume_state else {}
    dbg_history: list = list(resume_state["debug_history"]) if resume_state else []
    pre_blowup_checkpoint_written = False
    pre_blowup_checkpoint_announced = False
    last_pre_step_frame = None
    # Retain per-node control volumes from the current grid build for reuse.
    control_volumes = solver._grid.cell_volumes() if solver._alpha_grid > 1.0 else None

    while t < T and (max_steps is None or step < max_steps):
        dt_budget = None
        if cfg.run.dt_fixed is not None:
            dt_candidate = float(cfg.run.dt_fixed)
        else:
            dt_budget = solver.dt_budget(
                u,
                v,
                ph,
                cfg.run.cfl,
                cfl_advective=cfg.run.cfl_advective,
                cfl_capillary=cfg.run.cfl_capillary,
                cfl_viscous=cfg.run.cfl_viscous,
            )
            dt_candidate = float(dt_budget.dt)
        if resume_dt_candidate is not None:
            dt_candidate = float(resume_dt_candidate)
            resume_dt_candidate = None
        dt = min(dt_candidate, T - t)
        if dt < 1e-12:
            break
        terminal_clamped = bool(dt < dt_candidate - max(1.0e-15, 1.0e-12 * dt_candidate))
        pre_step_results = _merge_time_series(
            previous_results,
            {**diag.to_arrays()},
        )
        p_pre = _checkpoint_pressure(solver, p, psi)
        last_pre_step_frame = capture_checkpoint_frame(
            solver=solver,
            psi=psi,
            u=u,
            v=v,
            p=p_pre,
            t=t,
            step=step,
            config_path=config_path,
            results=pre_step_results,
            snapshots=snaps,
            debug_history=dbg_history,
            state_phase="pre_step",
            dt_candidate=dt_candidate,
            dt_effective=dt,
            terminal_clamped=terminal_clamped,
        )
        if (
            checkpoint_every_steps is not None
            and continuation_path is not None
            and checkpoint_every_steps > 0
            and step > 0
            and step % checkpoint_every_steps == 0
        ):
            write_checkpoint_frame(continuation_path, last_pre_step_frame)
        will_snapshot = snap_idx < len(snap_times) and t + dt >= snap_times[snap_idx]
        solver._record_interface_projection_fields = bool(
            will_snapshot and _snapshot_needs_projection_fields(cfg)
        )

        step_index = step
        grid_will_rebuild = (
            solver._alpha_grid > 1.0
            and solver._rebuild_freq > 0
            and step_index > 0
            and (step_index % solver._rebuild_freq == 0)
        )
        psi, u, v, p = solver.step_request(
            NSStepRequest(
                psi=psi,
                u=u,
                v=v,
                dt=dt,
                rho_l=ph.rho_l,
                rho_g=ph.rho_g,
                sigma=ph.sigma,
                mu=ph.mu,
                g_acc=ph.g_acc,
                rho_ref=ph.rho_ref,
                mu_l=ph.mu_l,
                mu_g=ph.mu_g,
                bc_hook=bc_hook,
                step_index=step_index,
            ),
            return_host_pressure=False,
        )
        t += dt
        step += 1

        _bk = solver._backend
        if grid_will_rebuild:
            control_volumes = solver._grid.cell_volumes()
            if diag.needs_retained_geometry():
                diag.X = solver.X
                diag.Y = solver.Y
                diag.retain_device_geometry(_bk.xp, solver.X, solver.Y, psi.shape)
        diag.collect(t, psi, u, v, _bk.xp.asarray(p), dV=control_volumes)
        dbg_entry = solver._step_diag.last
        if dbg_entry or (cfg.run.debug_diagnostics and dt_budget is not None):
            merged_diag = {"t": t, "step": step, **dbg_entry}
            if cfg.run.debug_diagnostics and dt_budget is not None:
                merged_diag.update(dt_budget.diagnostics())
            dbg_history.append(merged_diag)

        while snap_idx < len(snap_times) and t >= snap_times[snap_idx]:
            snaps.append(_capture_runtime_snapshot(solver, ph, t, psi, u, v, p))
            snap_idx += 1
        # Time checkpoints are observational.  They must not clamp ``dt`` or
        # alter the discrete flow map; store the restartable input state that
        # was actually used for the step crossing the requested checkpoint.
        while (
            checkpoint_interval is not None
            and checkpoint_path is not None
            and next_time_checkpoint is not None
            and _time_reached(t, next_time_checkpoint)
        ):
            time_path = _time_checkpoint_path(checkpoint_path, next_time_checkpoint)
            if last_pre_step_frame is not None:
                write_checkpoint_frame(time_path, last_pre_step_frame)
                frame_time = float(last_pre_step_frame["manifest"]["time"])
                print(
                    f"  [checkpoint] saved {time_path.name} "
                    f"from pre-step t={frame_time:.8g} "
                    f"(target {next_time_checkpoint:.8g})"
                )
            next_time_checkpoint = _next_time_checkpoint(
                next_time_checkpoint,
                checkpoint_interval,
                T,
            )

        if step % cfg.run.print_every == 0 or step <= 2:
            ke = diag.last("kinetic_energy", 0.0)
            print(f"  step={step:5d}  t={t:.4f}  dt={dt:.5f}  KE={ke:.3e}")
            if dt_budget is not None:
                print(
                    f"          dt_adv={dt_budget.dt_advective:.3e}  "
                    f"dt_visc={dt_budget.dt_viscous:.3e}  "
                    f"dt_cap={dt_budget.dt_capillary:.3e}  "
                    f"limiter={dt_budget.limiter}"
                )
            d = solver._step_diag.last
            if d:
                print(
                    f"          kappa_max={d['kappa_max']:.3e}  "
                    f"ppe_rhs={d['ppe_rhs_max']:.3e}  "
                    f"bf_res={d['bf_residual_max']:.3e}  "
                    f"div_u={d['div_u_max']:.3e}"
                )

        ke = diag.last("kinetic_energy", 0.0)
        if _is_blowup_kinetic_energy(ke):
            if pre_blowup_path is not None and last_pre_step_frame is not None:
                write_checkpoint_frame(pre_blowup_path, last_pre_step_frame)
                pre_blowup_checkpoint_written = True
                print(
                    "  [pre-blowup] saved input frame "
                    f"{pre_blowup_path.name} for the failed step"
                )
            print(f"  BLOWUP at step={step}, t={t:.4f}")
            break
        if pre_blowup_path is not None and _should_refresh_pre_blowup_checkpoint(ke):
            if not pre_blowup_checkpoint_announced:
                print(
                    "  [pre-blowup] refreshing input frame "
                    f"{pre_blowup_path.name} while KE is near the guard limit"
                )
                pre_blowup_checkpoint_announced = True
            if last_pre_step_frame is not None:
                write_checkpoint_frame(pre_blowup_path, last_pre_step_frame)
            pre_blowup_checkpoint_written = True
        if (
            checkpoint_every_steps is not None
            and checkpoint_path is not None
            and checkpoint_every_steps > 0
            and step % checkpoint_every_steps == 0
        ):
            current_results = _merge_time_series(
                previous_results,
                {**diag.to_arrays()},
            )
            save_checkpoint(
                checkpoint_path,
                solver=solver,
                psi=psi,
                u=u,
                v=v,
                p=p,
                t=t,
                step=step,
                config_path=config_path,
                results=current_results,
                snapshots=snaps,
                debug_history=dbg_history,
                state_phase="post_step",
            )

    results = _merge_time_series(previous_results, {**diag.to_arrays()})
    results["snapshots"] = snaps
    results["pre_blowup_checkpoint_written"] = np.asarray(
        pre_blowup_checkpoint_written,
        dtype=bool,
    )
    if dbg_history:
        results["debug_diagnostics"] = {
            key: np.array([entry[key] for entry in dbg_history]) for key in dbg_history[0]
        }
    if checkpoint_path is not None:
        if continuation_path is not None and last_pre_step_frame is not None:
            write_checkpoint_frame(continuation_path, last_pre_step_frame)
        p_save = p if p is not None else solver._backend.xp.zeros_like(psi)
        save_checkpoint(
            checkpoint_path,
            solver=solver,
            psi=psi,
            u=u,
            v=v,
            p=p_save,
            t=t,
            step=step,
            config_path=config_path,
            results={k: v for k, v in results.items() if isinstance(v, np.ndarray)},
            snapshots=snaps,
            debug_history=dbg_history,
            state_phase="post_step",
        )
    return results


def _is_blowup_kinetic_energy(ke: float) -> bool:
    """Return whether the run should fail closed on kinetic-energy growth."""
    return bool(np.isnan(ke) or ke > BLOWUP_KINETIC_ENERGY_LIMIT)


def _should_refresh_pre_blowup_checkpoint(ke: float) -> bool:
    """Return whether a successful state is close enough to preserve.

    The file is a restart artifact for diagnosis, not a stabilisation device:
    only finite, still-subcritical states are written, and the actual BLOWUP
    condition remains fail-closed.
    """
    if not np.isfinite(ke):
        return False
    lower = BLOWUP_KINETIC_ENERGY_LIMIT * PRE_BLOWUP_CHECKPOINT_FRACTION
    return bool(lower <= ke <= BLOWUP_KINETIC_ENERGY_LIMIT)


def _pre_blowup_checkpoint_path(checkpoint_path: str | Path) -> Path:
    """Return the sibling pre-step frame used for pre-failure diagnosis."""
    return Path(checkpoint_path).with_name("checkpoint_pre_blowup_input.npz")


def _continuation_checkpoint_path(checkpoint_path: str | Path) -> Path:
    """Return the sibling pre-step frame for exact continuation restarts."""
    return Path(checkpoint_path).with_name("checkpoint_continuation.npz")


def _normalise_checkpoint_interval(value) -> float | None:
    if value is None:
        return None
    interval = float(value)
    if interval <= 0.0:
        return None
    return interval


def _next_time_checkpoint(
    t: float,
    interval: float | None,
    final_time: float,
) -> float | None:
    if interval is None or not np.isfinite(final_time):
        return None
    index = int(np.floor(max(0.0, t) / interval + 1.0e-9)) + 1
    target = index * interval
    if target > final_time + max(1.0e-12, 1.0e-9 * abs(final_time)):
        return None
    return float(min(target, final_time))


def _time_reached(t: float, target: float) -> bool:
    tol = max(1.0e-12, 1.0e-9 * max(abs(t), abs(target), 1.0))
    return bool(t + tol >= target)


def _time_checkpoint_path(checkpoint_path: str | Path, time_value: float) -> Path:
    """Return a restartable checkpoint path keyed by physical time."""
    path = Path(checkpoint_path)
    label = f"{time_value:.9f}".rstrip("0").rstrip(".").replace(".", "p")
    return path.with_name(f"checkpoint_t{label}.npz")


def _checkpoint_pressure(solver, p, psi):
    """Return a pressure array suitable for checkpoint payloads."""
    if p is not None:
        return p
    return solver._backend.xp.zeros_like(psi)


def _capture_runtime_snapshot(solver, ph, t: float, psi, u, v, p) -> dict:
    """Capture host arrays consumed by snapshot figures and restart artifacts."""
    backend = solver._backend

    def to_host_array(value):
        return np.asarray(backend.to_host(value))

    psi_h = to_host_array(psi)
    u_h = to_host_array(u)
    v_h = to_host_array(v)
    p_h = to_host_array(p)
    snap_entry = {
        "t": float(t),
        "psi": psi_h.copy(),
        "u": u_h.copy(),
        "v": v_h.copy(),
        "p": p_h.copy(),
        "rho": (ph.rho_l * psi_h + ph.rho_g * (1.0 - psi_h)).copy(),
    }
    if solver._p_prev_accel_face_components is not None:
        snap_entry["pressure_accel_faces"] = [
            to_host_array(component).copy()
            for component in solver._p_prev_accel_face_components
        ]
    projection_fields = getattr(solver, "_last_interface_projection_fields", None)
    if projection_fields:
        for field in PROJECTION_SNAPSHOT_FIELDS:
            if field in projection_fields:
                snap_entry[field] = to_host_array(projection_fields[field]).copy()
    if solver._alpha_grid > 1.0:
        snap_entry["grid_coords"] = [c.copy() for c in solver._grid.coords]
    return snap_entry


def _snapshot_needs_projection_fields(cfg: "ExperimentConfig") -> bool:
    """Return whether configured snapshot figures consume reinit intermediates."""
    for figure in getattr(cfg.output, "figures", []) or []:
        if not isinstance(figure, dict):
            continue
        if (
            figure.get("type") == "snapshot_series"
            and figure.get("field") in PROJECTION_SNAPSHOT_FIELDS
        ):
            return True
    return False


def _merge_time_series(
    previous: dict[str, np.ndarray],
    current: dict[str, np.ndarray],
) -> dict[str, np.ndarray]:
    """Concatenate diagnostic arrays loaded from checkpoint with new samples."""
    merged: dict[str, np.ndarray] = {}
    for key, value in previous.items():
        if isinstance(value, np.ndarray):
            merged[key] = value.copy()
    for key, value in current.items():
        if not isinstance(value, np.ndarray):
            continue
        if key in merged and merged[key].ndim == value.ndim:
            merged[key] = np.concatenate([merged[key], value])
        else:
            merged[key] = value
    return merged
