# §8: Pressure-velocity coupling — GFM, PPE RHS, velocity correction
from .capillary_geometry import apply_wall_compatible_curvature
from .closed_interface_geometry import (
    fixed_stratum_directional_derivative_check,
    liquid_area_2d,
    liquid_area_gradient_2d,
    trace_surface_length_2d,
    trace_surface_length_gradient_2d,
)
from .closed_interface_riesz import (
    ClosedInterfaceRieszCochain,
    ComponentReactionHodgeGate,
    VirtualWorkCheck,
    WeightedHodgeDecomposition,
    closed_interface_riesz_cochain,
    component_reaction_hodge_gate,
    face_mass_components,
    face_measure_components,
    face_weighted_dot,
    face_weighted_norm,
    fixed_stratum_virtual_work_check,
    transport_increment_from_face_velocity,
    weighted_hodge_decomposition,
)
from .closed_interface_stratum import (
    ClosedInterfaceStratum,
    build_closed_interface_stratum,
)
from .closed_interface_trace import (
    TraceComponent2D,
    TraceGraph2D,
    TraceSegment2D,
    TraceVertex2D,
    build_trace_graph_2d,
    trace_component_area_vertex_covectors,
    trace_component_areas,
    trace_graph_surface_length,
    trace_surface_vertex_covectors,
)
from .closed_interface_trace_riesz import (
    ClosedInterfaceTraceRieszCochain,
    TraceComponentHodgeProjection,
    TraceRieszWorkCheck,
    TraceStaticCriticality,
    closed_interface_trace_riesz_cochain,
    trace_component_hodge_projection,
    trace_hodge_weighted_l2,
    trace_riesz_work_check,
    trace_static_criticality,
    trace_vertex_static_criticality,
)
from .closed_interface_trace_velocity import (
    ReconstructedNodalP1TraceVelocityMap,
    face_vertex_vjp_residual,
)
from .phase_region_force_admission import (
    FixedStratumVelocityScale,
    PhaseRegionForceAdapterDecision,
    PhaseRegionForceDiagnostics,
    PhaseRegionForceAdmission,
    PhaseRegionForceAdmissionReport,
    PhaseRegionFaceMassMetric,
    attach_phase_region_force_diagnostics,
    build_phase_region_force_adapter_decision,
    build_phase_region_force_admission_candidate,
    build_phase_region_force_admission_report,
    phase_region_face_mass_metric,
    scale_face_velocity_to_fixed_stratum,
    two_phase_nodal_density,
)
from .gfm import GFMCorrector
from .interface_stress_closure import (
    InterfaceStressContext,
    build_interface_stress_context,
    build_young_laplace_interface_stress_context,
    evaluate_interface_face_curvature_lg,
    interface_stress_context_is_active,
    signed_pressure_jump_gradient,
)
from .velocity_corrector import VelocityCorrector
from .ppe_rhs_gfm import PPERHSBuilderGFM

__all__ = [
    "GFMCorrector",
    "InterfaceStressContext",
    "VelocityCorrector",
    "ClosedInterfaceStratum",
    "ClosedInterfaceRieszCochain",
    "ClosedInterfaceTraceRieszCochain",
    "ComponentReactionHodgeGate",
    "FixedStratumVelocityScale",
    "PPERHSBuilderGFM",
    "PhaseRegionForceAdapterDecision",
    "PhaseRegionForceDiagnostics",
    "PhaseRegionForceAdmission",
    "PhaseRegionForceAdmissionReport",
    "PhaseRegionFaceMassMetric",
    "ReconstructedNodalP1TraceVelocityMap",
    "TraceComponent2D",
    "TraceComponentHodgeProjection",
    "TraceGraph2D",
    "TraceRieszWorkCheck",
    "TraceSegment2D",
    "TraceStaticCriticality",
    "TraceVertex2D",
    "VirtualWorkCheck",
    "WeightedHodgeDecomposition",
    "apply_wall_compatible_curvature",
    "build_interface_stress_context",
    "build_closed_interface_stratum",
    "build_phase_region_force_adapter_decision",
    "build_phase_region_force_admission_candidate",
    "build_phase_region_force_admission_report",
    "build_trace_graph_2d",
    "attach_phase_region_force_diagnostics",
    "build_young_laplace_interface_stress_context",
    "closed_interface_riesz_cochain",
    "closed_interface_trace_riesz_cochain",
    "component_reaction_hodge_gate",
    "evaluate_interface_face_curvature_lg",
    "face_mass_components",
    "face_measure_components",
    "face_vertex_vjp_residual",
    "face_weighted_dot",
    "face_weighted_norm",
    "fixed_stratum_directional_derivative_check",
    "fixed_stratum_virtual_work_check",
    "interface_stress_context_is_active",
    "liquid_area_2d",
    "liquid_area_gradient_2d",
    "phase_region_face_mass_metric",
    "scale_face_velocity_to_fixed_stratum",
    "signed_pressure_jump_gradient",
    "trace_component_area_vertex_covectors",
    "trace_component_areas",
    "trace_component_hodge_projection",
    "trace_graph_surface_length",
    "trace_hodge_weighted_l2",
    "trace_riesz_work_check",
    "trace_static_criticality",
    "trace_surface_vertex_covectors",
    "trace_surface_length_2d",
    "trace_surface_length_gradient_2d",
    "trace_vertex_static_criticality",
    "transport_increment_from_face_velocity",
    "two_phase_nodal_density",
    "weighted_hodge_decomposition",
]
